-- CreateTable
CREATE TABLE "vms" (
    "id" SERIAL NOT NULL,
    "no" INTEGER,
    "namaList" TEXT,
    "kondisi" TEXT,
    "cluster" TEXT,
    "host" TEXT,
    "compatibility" TEXT,
    "guestOs" TEXT,
    "provisionedSpace" TEXT,
    "usedSpace" TEXT,
    "memorySize" TEXT,
    "cpus" INTEGER,
    "nics" INTEGER,
    "ipAddress" TEXT,
    "uuid" TEXT,
    "uptime" TEXT,
    "datastore" TEXT,
    "application" TEXT,
    "component" TEXT,
    "kritikalitas" TEXT,
    "category" TEXT,
    "notes" TEXT,
    "osDetail" TEXT,
    "ipDetail" TEXT,
    "maOwner" TEXT,
    "maOps" TEXT,
    "maDev" TEXT,
    "vcenter" TEXT,
    "endSupportDate" TEXT,
    "statusOs" TEXT,
    "detailStatus" TEXT,
    "keterangan" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "vms_pkey" PRIMARY KEY ("id")
);
